sonar.projectKey=smontel-bobapp
sonar.organization=smontel

# Back-end
sonar.sources=back/src/main/java
sonar.tests=back/src/test/java
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# Front-end
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info