sonar.projectKey=smontel_bobapp_front
sonar.organization=smontel
sonar.sources=src
sonar.tests=src
sonar.coverage.exclusions=src/main.ts,src/polyfills.ts,src/environments/**
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info