sonar.projectKey=smontel_bobapp_front
sonar.organization=smontel
sonar.sources=src
sonar.exclusions=**/*.spec.ts, src/test.ts, src/main.ts, src/environments/environment.prod.ts, src/environments/environment.ts
sonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
